name: pack

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get commit hash
        id: vars
        run: |
          shortHash=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_HASH=$shortHash" >> $GITHUB_ENV
      - name: Copy license
        run: |
          cp LICENSE existence_community_resource_pack/LICENSE
      - name: Zip
        run: |
          zip -r existence_community_resource_pack.zip existence_community_resource_pack
      # - name: Squash
      #   uses: ComunidadAylas/PackSquash-action@v4
      #   with:
      #     packsquash_version: latest
      #     options: |
      #       pack_directory = './existence_community_resource_pack'
      #       output_file_path = './existence_community_resource_pack.zip'
      #       zip_spec_conformance_level = 'balanced'
      #       recompress_compressed_files = true
      #       ignore_system_and_hidden_files = false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: existence_community_resource_pack.zip
          tag_name: ${{ env.COMMIT_SHORT_HASH }}
